name: FI3 Status Update

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Update status message (embed)
        run: node update-status.js
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_MESSAGE_ID: ${{ secrets.DISCORD_MESSAGE_ID }}
